baseURL: https://anaanyachopra.netlify.app/
languageCode: en-us
title: Portfolio for Anaanya Chopra
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A Porfolio showcasing my work as data analytics student
    title: Hi, my name is Anaanya
  blog: {I am currently a Masters in Financial Analysis Student at London Business School.My hometown is Mumbai, India and I did my undergraduate degree in Economics and Statistics from Mumbai University}
  contact:
    address:
      - city: London, NW1 4SA
        country: England
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: achopra.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7651786578 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer: 
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
  #    - #icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
  #    - #icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Anaanyachopra/my_website
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/anaanyachopra/
  image: ''
  name: Anaanya
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: About myself
        url: blogs/aliquam
        
      #- name: Generic Blog
        #url: blogs/ipsum
      #- #name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Introducing myself - A short background
        title: About myself
        url: blogs/aliquam
      - image: Recession_1.jpg
        subtitle: Can yield curves predict recessions?
        title: Macroeconomic indicators
        url: blogs/tempus
      - image: Gender disparity_1.jpg
        subtitle: Workspace discrimination through the lens of statistics
        title: Gender Disparity 
        url: blogs/magna
      - image: Climate Change.jpg
        subtitle: To show the effects of climate change through temperature deviations per year and per month
        title: Climate Change Analysis
        url: blogs/ipsum
      - image: Inflation_1.jpg
        subtitle: Seeing how the CPI and its components change over time
        title: Measuring Inflation
        url: blogs/test1
      - image: Berlin_1.jpg
        subtitle: Data exploration and analysis for Air BnB's in Berlin
        title: Air BnB Evaluation
        url: blogs/test2
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "This is a blog showing my work manipulating data and using it to study different types of projetcs. I have used multiple different files to conduct exploratory data analysis and used coding specifically for data visualization. A lot of this data has been used not only to conduct actual statistical tests, but also to get a feel of the datasets in general."
    title: What is this?
    url: blogs
    
